---
- name: Sprawdzenie połączenia z hostami
  hosts: all
  gather_facts: false
  tasks:
    - name: Czekanie na dostępność SSH
      wait_for_connection:
        timeout: 300
        delay: 10

- name: Konfiguracja podstawowa wszystkich hostów
  hosts: all
  become: true
  roles:
    - common

- name: Konfiguracja serwera głównego
  hosts: srv-main
  become: true
  serial: 1
  roles:
    - freeipa
    - dhcp
    - samba
    - apache
    - gitlab
    - openvpn

- name: Konfiguracja serwera backup
  hosts: srv-backup
  become: true
  roles:
    - bacula

- name: Konfiguracja klientów
  hosts: clients
  become: true
  roles:
    - client
